Pin bw2calc, as version 2 contains breaking changes
Eg. `ImportError: cannot import name 'ParallelMonteCarlo' from
'bw2calc'`
Version 2.0.dev2 was released 2021-10-01, which is otherwise installed
by default without this pinning.